"""Add User model

Revision ID: e27ba59f0786
Revises: 6c5c2f115931
Create Date: 2025-06-16 15:44:38.663376

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e27ba59f0786"
down_revision = "6c5c2f115931"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.drop_table("diagrams")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "diagrams",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("root_name", sa.VARCHAR(length=120), nullable=False),
        sa.Column("diagram_name", sa.VARCHAR(length=120), nullable=False),
        sa.Column("diagram_type", sa.VARCHAR(length=50), nullable=True),
        sa.Column("file_path", sa.VARCHAR(length=255), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("user")
    # ### end Alembic commands ###
